package tong.lan.com.hyperledger.domain;
// Generated 2017-7-29 17:34:30 by Hibernate Tools 3.4.0.CR1

import org.litepal.crud.DataSupport;

import java.util.ArrayList;
import java.util.List;

/**
 * Employee generated by hbm2java
 */
public class Employee extends DataSupport {
	private Integer id;
	private String employeeName;
	private List<Record> record = new ArrayList<>();//一个员工对应多条生产记录


	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public List<Record> getRecord() {
		return record;
	}

	public void setRecord(List<Record> record) {
		this.record = record;
	}

	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}
}
