package tong.lan.com.hyperledger.domain;
// Generated 2017-7-29 17:34:30 by Hibernate Tools 3.4.0.CR1

import org.litepal.crud.DataSupport;

import java.util.ArrayList;
import java.util.List;

/**
 * Product generated by hbm2java
 */
public class Product extends DataSupport {
	private int id;
	private String Name;//产品名称
	private double Wage;//工人工价
	private List<Make> make;//一个产品对应多条生产记录

	public Product(String Name, double Wage) {
		this.Name = Name;
		this.Wage = Wage;
		make = new ArrayList<Make>();
	}

	public Product() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public List<Make> getMake() {
		return make;
	}

	public void setMake(List<Make> make) {
		this.make = make;
	}

	public String getName() {
		return this.Name;
	}

	public void setName(String name) {
		this.Name = name;
	}

	public double getWage() {
		return this.Wage;
	}

	public void setWage(double wage) {
		this.Wage = wage;
	}
}
