package tong.lan.com.hyperledger.domain;
// Generated 2017-7-29 17:34:30 by Hibernate Tools 3.4.0.CR1

import org.litepal.crud.DataSupport;

import java.util.Date;

/**
 * Make generated by hbm2java
 */
public class Record extends DataSupport {

	private int id;
	private Employee employee;
	private Product product;
	private Date date;
	private Integer amount;

	public Record(Employee employee, Product product, Date date, Integer amount) {
		this.employee = employee;
		this.product = product;
		this.date = date;
		this.amount = amount;
	}

	public Record() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

}
